### ISSUE TITLE
make: *** No rule to make target 'install'.  Stop.

### ISSUE THREAD

**Issue by Sh-Fang** [develancer/empi#2]
hi, I'm trying to compile empi from source, but there are some problem.

After runing "sudo make install“,  I was trying to run "sudo make install", but it prompts me “make: *** No rule to make target 'install'.  Stop.”

Like is:
![image](https://user-images.githubusercontent.com/46022639/221363566-4b340c7d-19a3-4914-a522-98f6f8765afb.png)

**Comment by develancer** [comment]
Thank you @Sh-Fang for reporting this. I haven’t noticed that before. It must have stopped working at the last rewrite of CMakeLists. I’ll try to fix it soon.

In the meantime, you can simply use the “empi” executable file which should reside in the current directory after a successful invocation of `make`. You can use it as `./empi` or move it to suitable user or system directory e.g. `/usr/local/bin`.

**Comment by Sh-Fang** [comment]
Thank you for your reply, this is very helpful for me !

But there are another problem when I try to use `empi input_file output_file` 

it prompts me `ERROR   missing configuration entry`. Like this:

![image](https://user-images.githubusercontent.com/46022639/221389058-8eadaa24-6229-4027-83d0-c8a9f319d66a.png)

Maybe I did something wrong, but I don't know where it is. (Below is my code to open the signal file and the signal file)

```
import numpy as np
import pylab

# open signal file
with open('./signal') as f:
    signal = np.fromfile(f,dtype='float32')

# show signal file
pylab.plot(signal)
print("signal shape:",signal.shape)
```

![image](https://user-images.githubusercontent.com/46022639/221389400-79c8b65d-4f29-4e07-b8a9-851ebff1ed81.png)

**Comment by develancer** [comment]
You’re using the 0.9.7 release which uses the configuration files instead of command-line parameters. Please consult the README.md for your specific version, it should be included in the repository. For this specific version

> empi needs to be run with a single command-line argument: a path to the configuration file. If run with no arguments, it will print the correct usage. Default output format is SQLite; however, if `-j` is given as an argument, JSON output file will be created instead.

If you want to use the command-line version, simply check out the repository from the master branch instead.

**Comment by Sh-Fang** [comment]
Sincerely thank you for your help, it is very helpful to my work ! 

Wish you have a happy life!

**Comment by develancer** [comment]
`make install` is now fixed on the master branch.
