### ISSUE TITLE
make empi > fatal error: 'fftw3.h' file not found

### ISSUE THREAD

**Issue by ywang171** [develancer/empi#4]
Hello Dr. Różański,

I'm trying to install **empi** on MacOS, and have a quick question regarding the **_make empi_** (I'm new to c++, so this might be an easy question). I've installed **cmake** (3.27.7) and **fftw** (3.3.10_1), but when I ran **_make empi_**, I got an error showing that:
**.../empi-1.0.1/src/SpectrogramCalculatorFFTW.cpp:7:10: fatal error: 'fftw3.h' file not found**

I checked on the Terminal showing that the **fftw3.h** is linked under the folder **/usr/local/include/**. I was wondering if I should specify the location of this header file to c++ compiler in the **build.make** under **empi-cpu.dir** folder, or if you have any suggestions on this issue. Thank you so much.

**Comment by develancer** [comment]
I’m not sure if MacOS includes `/usr/local/include` in its default include path. How did you install FFTW? I would suggest to install it with homebrew (`brew install fftw`) and see if it helps.

I didn’t have any luck compiling empi with clang, but I might have had some outdated version. GCC did the trick, though.

**Comment by ywang171** [comment]
I installed **cmake** and **fftw** by **_brew_**. I've also tried to export `/usr/local/include` to PATH, but didn't work.

**Comment by ywang171** [comment]
I added `CXX_FLAGS += -I/usr/local/include` in two **flags.make** files under **CMakeFiles/empi-cpu.dir** and **CMakeFiles/empi.dir** folder, and it works even though one warning came out with `..../empi-1.0.1/include/ExtenderLoop.h:26:13: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]` :
`atom->extend(true); // ExtendedAtomPointer will be put into cache`

Now I encountered a new error: 
`[ 97%] Linking CXX executable empi`
`ld: library 'fftw3' not found`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by ywang171** [comment]
quick update: successfully installed **empi** to the `/usr/local/bin/empi`

I basically added `CXX_FLAGS += -I/usr/local/include` to the **flags.make** file and `-L /usr/local/lib` to the **link.txt** file under the project folder which has the error with fftw3 header (`'fftw3.h' file not found`) or library (`ld: library 'fftw3' not found`). I believe there are many better and easier ways to solve the issue. 

Thank you so much again for your help and for sharing this powerful program.

**Comment by develancer** [comment]
Great, congratulations! I can’t say for sure what caused the problem, but there are two things I can share:
1. If you install any libraries (e.g. FFTW) after doing the initial `cmake` command, it may not be able to find this libraries later on, even if you re-issue the command. The right way would be start from scratch (from freshly cloned repository or after `git clean -fdx`) after each change in system configuration.
2. CMake-generated files are really not meant to be edited manually. Instead of changing flags.make and link.txt, a better idea would be to pass these flags through environment variables.
